name: PatternClass
version: 2.1
date: 27/08/2015
description: A permutation pattern class package

authors:
    - name: Ruth Hoffmann
      url: mailto:rh347@icloud.com
    - name: Steve Linton
      url: http://sal.host.cs.st-andrews.ac.uk/
    - name: Michael Albert
      url: http://www.cs.otago.ac.nz/staff/michael.html

maintainers:
    - name: Ruth Hoffmann
      url: mailto:rh347@icloud.com

GAP: ">=4.4"

needed-pkgs:
    - name: "Automata"
      version: ">=1.13"
      url: "http://www.fc.up.pt/cmup/mdelgado/automata"

www: http://ruthhoffmann.github.io/PatternClass/
readme: http://ruthhoffmann.github.io/PatternClass/README
packageinfo: http://ruthhoffmann.github.io/PatternClass/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/ruthhoffmann/PatternClass/releases/download/2.1/PatternClass2.1.tar.gz

abstract: This package allows basic permutation pattern calculations to happen. It especially concentrates on the formation of automata from token passing networks and the rank encoding of the output permutation of these networks.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
